# Generated by Django 5.0 on 2024-01-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='images/default_avatar.jpg', upload_to='avatars'),
        ),
    ]
