# Generated by Django 5.0 on 2024-01-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0004_remove_article_subject_article_type_delete_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='file',
            field=models.FileField(upload_to='media/articles'),
        ),
    ]
