# Generated by Django 5.0 on 2024-01-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0006_alter_article_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
