# Generated by Django 5.0 on 2024-01-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0007_article_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
