# Generated by Django 5.0 on 2024-01-06 16:52

import campus_app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0009_bpmn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BPMN',
        ),
        migrations.AlterField(
            model_name='article',
            name='file',
            field=models.FileField(upload_to='articles', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc']), campus_app.models.Article.file_size_validator]),
        ),
    ]
